### PR TITLE
fix: The month button arrow in DCalendarWidget is out of range

### PR DESCRIPTION
**Pull request by mhduiy**
If only text is displayed in PopupDelay mode and there is a menu, the text and arrows will be centered as a whole

Issue: https://github.com/linuxdeepin/developer-center/issues/7402

### CODE REVIEW

**Comment by mhduiy** [comment]
recheck

**Comment by mhduiy** [comment]
recheck

**Comment by hudeng-go** [comment]
recheck

**Comment by mhduiy** [comment]
修改后的效果图
image

**Review by FeiWang1119 — APPROVED** [review]

**Pull request merged**
